# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy Site to GitHub Pages

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        NODE_VERSION: 13.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js $NODE_VERSION
      uses: actions/setup-node@v1
      with:
        node-version: $NODE_VERSION
    - name: Build
      run: |
        npm ci
        npm run build --if-present
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: public # The folder the action should deploy.
      
